on: [issues, pull_request]
jobs:
  sync-labels:
    runs-on: ubuntu-latest
    name: Sync repository labels
    steps:
      - uses: woocommerce/woo-std-labels@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labels-path: ./labels.json
